# Generated by Django 4.2.5 on 2024-02-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charapters',
            new_name='Characters',
        ),
    ]
